[CI/CD] Creating release subproject for jenkins to preform releases
radanalyticsio/oshinko-console pull request #42
Opened 2017-01-26 20:07 UTC by zmhassan

OpenShift console extension only requires *.js, *.css files to run the extension on openshift. I want to trigger this build to cut a release so I can fetch it from github release page for this project instead of performing manual builds.

prerequisite is to have jenkins perform the following before cutting the release zip file
```bash
gem install bundler
sudo npm install
bower install
grunt build --force

```

2017-01-26 20:56 UTC, crobby requested changes
I think that since I merged the tweak to the deps that --force should no longer be needed.  If that's not the case, let me know and we will fix it.  Having --force in our real build seems bad.

2017-01-27 01:14 UTC, zmhassan commented
I've removed that from the instructions. I'd like to see if this can get merged as I've got the building running off my local fork with this branch

2017-01-27 01:16 UTC, zak-hassan reviewed
The code changes only effect the zip being created and not the prerequisite step required before creating the zip

2017-01-27 09:47 UTC, sub-mod commented
does the release get pushed to github?

2017-01-27 14:44 UTC, zmhassan commented
That is the next step in the process. For now this additional change only creates the zip there will be more work done on jenkins to do the full release

2017-01-30 14:13 UTC, crobby approved these changes

2017-01-30 22:20 UTC, zmhassan commented
The release gets posted as an artifact in jenkins. But I'm planning on integrating github release next. For now I'll need to get this merged before I do that next step.

2017-01-31 14:23 UTC, merged